version: 0.2

# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cd-pipeline.html
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 292025097823.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=292025097823.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-ecr:latest
      - IMAGE_TAG=$(echo release-$CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs-app-ecr .
      - docker tag nodejs-app-ecr:latest 292025097823.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      
      - echo Writing image definitions file...
      - printf '[{"name":"nodejs-app-ecr","imageUri":"%"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
